<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\View\View;

class DashboardController extends Controller
{
    /**
     * Display the Supply Chain Global Monitoring Dashboard.
     */
    public function index(Request $request): View
    {
        // High-fidelity dummy shipments data
        $shipments = [
            [
                'cargo_id' => 'CRG-2026-CN01',
                'origin_port' => 'Port of Shenzhen',
                'origin_city' => 'Shenzhen',
                'origin_country' => 'China',
                'origin_country_code' => 'CN',
                'origin_lat' => 22.4833,
                'origin_lng' => 113.8833,
                'destination_port' => 'Port of Los Angeles',
                'destination_city' => 'Los Angeles',
                'destination_country' => 'United States',
                'destination_country_code' => 'US',
                'destination_lat' => 33.7438,
                'destination_lng' => -118.2673,
                'current_lat' => 28.1250,
                'current_lng' => 172.4800,
                'status' => 'Port Congestion',
                'risk_level' => 'High',
                'transport_mode' => 'Sea',
                'eta' => '2026-07-15 08:00:00',
                'carrier_name' => 'Maersk Line',
                'vessel_name' => 'Maersk Mc-Kinney Moller',
                'imo_number' => '9632064',
                'speed' => 12.5,
                'heading' => 72,
                'container_temp_history' => [20, 20, 21, 21, 22, 22, 23, 23, 22, 21],
                'container_humidity_history' => [65, 66, 66, 67, 67, 68, 68, 67, 66, 66],
                'document_bill_of_lading' => 'Approved',
                'document_certificate_of_origin' => 'Approved',
                'document_commercial_invoice' => 'Under Review',
                'document_packing_list' => 'Approved',
                'document_customs_declaration' => 'Pending',
                'value' => 425000.00,
                'currency' => 'USD',
            ],
            [
                'cargo_id' => 'CRG-2026-DE02',
                'origin_port' => 'Port of Hamburg',
                'origin_city' => 'Hamburg',
                'origin_country' => 'Germany',
                'origin_country_code' => 'DE',
                'origin_lat' => 53.5511,
                'origin_lng' => 9.9937,
                'destination_port' => 'Port of Tanjung Priok',
                'destination_city' => 'Jakarta',
                'destination_country' => 'Indonesia',
                'destination_country_code' => 'ID',
                'destination_lat' => -6.1030,
                'destination_lng' => 106.8833,
                'current_lat' => 11.2333,
                'current_lng' => 51.5667,
                'status' => 'In-Transit',
                'risk_level' => 'Medium',
                'transport_mode' => 'Sea',
                'eta' => '2026-07-28 14:00:00',
                'carrier_name' => 'Hapag-Lloyd',
                'vessel_name' => 'Hamburg Express',
                'imo_number' => '9461013',
                'speed' => 18.2,
                'heading' => 125,
                'container_temp_history' => [18, 18, 19, 19, 20, 21, 22, 23, 24, 25],
                'container_humidity_history' => [60, 61, 62, 63, 65, 68, 70, 72, 73, 75],
                'document_bill_of_lading' => 'Approved',
                'document_certificate_of_origin' => 'Approved',
                'document_commercial_invoice' => 'Approved',
                'document_packing_list' => 'Approved',
                'document_customs_declaration' => 'Under Review',
                'value' => 285000.00,
                'currency' => 'EUR',
            ],
            [
                'cargo_id' => 'CRG-2026-JP03',
                'origin_port' => 'Port of Yokohama',
                'origin_city' => 'Yokohama',
                'origin_country' => 'Japan',
                'origin_country_code' => 'JP',
                'origin_lat' => 35.4430,
                'origin_lng' => 139.6380,
                'destination_port' => 'Port of Singapore',
                'destination_city' => 'Singapore',
                'destination_country' => 'Singapore',
                'destination_country_code' => 'SG',
                'destination_lat' => 1.2902,
                'destination_lng' => 103.8519,
                'current_lat' => 1.2902,
                'current_lng' => 103.8519,
                'status' => 'Customs Cleared',
                'risk_level' => 'Low',
                'transport_mode' => 'Sea',
                'eta' => '2026-07-02 10:00:00',
                'carrier_name' => 'Ocean Network Express (ONE)',
                'vessel_name' => 'ONE Apus',
                'imo_number' => '9847865',
                'speed' => 0.0,
                'heading' => 180,
                'container_temp_history' => [15, 15, 16, 16, 15, 15, 16, 16, 16, 16],
                'container_humidity_history' => [55, 55, 56, 56, 55, 54, 55, 56, 56, 56],
                'document_bill_of_lading' => 'Approved',
                'document_certificate_of_origin' => 'Approved',
                'document_commercial_invoice' => 'Approved',
                'document_packing_list' => 'Approved',
                'document_customs_declaration' => 'Approved',
                'value' => 68400000.00,
                'currency' => 'JPY',
            ],
            [
                'cargo_id' => 'CRG-2026-NL04',
                'origin_port' => 'Port of Rotterdam',
                'origin_city' => 'Rotterdam',
                'origin_country' => 'Netherlands',
                'origin_country_code' => 'NL',
                'origin_lat' => 51.9244,
                'origin_lng' => 4.4777,
                'destination_port' => 'Port of New York',
                'destination_city' => 'New York',
                'destination_country' => 'United States',
                'destination_country_code' => 'US',
                'destination_lat' => 40.7128,
                'destination_lng' => -74.0060,
                'current_lat' => 40.6892,
                'current_lng' => -74.0445,
                'status' => 'Demurrage Risk',
                'risk_level' => 'High',
                'transport_mode' => 'Sea',
                'eta' => '2026-07-01 17:00:00',
                'carrier_name' => 'CMA CGM',
                'vessel_name' => 'CMA CGM Marco Polo',
                'imo_number' => '9607423',
                'speed' => 1.1,
                'heading' => 285,
                'container_temp_history' => [4, 4, 5, 5, 5, 6, 6, 6, 7, 7],
                'container_humidity_history' => [40, 41, 40, 42, 42, 43, 44, 43, 45, 45],
                'document_bill_of_lading' => 'Approved',
                'document_certificate_of_origin' => 'Under Review',
                'document_commercial_invoice' => 'Approved',
                'document_packing_list' => 'Approved',
                'document_customs_declaration' => 'Pending',
                'value' => 195000.00,
                'currency' => 'EUR',
            ],
            [
                'cargo_id' => 'CRG-2026-US05',
                'origin_port' => 'O\'Hare International Airport',
                'origin_city' => 'Chicago',
                'origin_country' => 'United States',
                'origin_country_code' => 'US',
                'origin_lat' => 41.9742,
                'origin_lng' => -87.9073,
                'destination_port' => 'Heathrow Airport',
                'destination_city' => 'London',
                'destination_country' => 'United Kingdom',
                'destination_country_code' => 'GB',
                'destination_lat' => 51.4700,
                'destination_lng' => -0.4543,
                'current_lat' => 52.3000,
                'current_lng' => -32.5000,
                'status' => 'In-Transit',
                'risk_level' => 'Low',
                'transport_mode' => 'Air',
                'eta' => '2026-07-03 04:30:00',
                'carrier_name' => 'FedEx Express',
                'vessel_name' => 'Boeing 777-F',
                'imo_number' => 'F-FX777',
                'speed' => 480.0,
                'heading' => 82,
                'container_temp_history' => [18, 18, 17, 17, 16, 16, 15, 15, 15, 15],
                'container_humidity_history' => [30, 29, 28, 28, 28, 27, 27, 26, 26, 26],
                'document_bill_of_lading' => 'Approved',
                'document_certificate_of_origin' => 'Approved',
                'document_commercial_invoice' => 'Approved',
                'document_packing_list' => 'Approved',
                'document_customs_declaration' => 'Approved',
                'value' => 75000.00,
                'currency' => 'USD',
            ],
            [
                'cargo_id' => 'CRG-2026-CN06',
                'origin_port' => 'Port of Shanghai',
                'origin_city' => 'Shanghai',
                'origin_country' => 'China',
                'origin_country_code' => 'CN',
                'origin_lat' => 31.2222,
                'origin_lng' => 121.4581,
                'destination_port' => 'Port of Rotterdam',
                'destination_city' => 'Rotterdam',
                'destination_country' => 'Netherlands',
                'destination_country_code' => 'NL',
                'destination_lat' => 51.9244,
                'destination_lng' => 4.4777,
                'current_lat' => 12.1167,
                'current_lng' => 43.4333,
                'status' => 'In-Transit',
                'risk_level' => 'Medium',
                'transport_mode' => 'Sea',
                'eta' => '2026-07-20 22:00:00',
                'carrier_name' => 'COSCO Shipping',
                'vessel_name' => 'COSCO Shipping Universe',
                'imo_number' => '9810570',
                'speed' => 19.5,
                'heading' => 320,
                'container_temp_history' => [14, 14, 15, 15, 16, 17, 18, 19, 19, 20],
                'container_humidity_history' => [48, 49, 50, 52, 55, 58, 62, 65, 68, 70],
                'document_bill_of_lading' => 'Approved',
                'document_certificate_of_origin' => 'Approved',
                'document_commercial_invoice' => 'Under Review',
                'document_packing_list' => 'Under Review',
                'document_customs_declaration' => 'Pending',
                'value' => 1250000.00,
                'currency' => 'CNY',
            ],
            [
                'cargo_id' => 'CRG-2026-AU07',
                'origin_port' => 'Sydney Airport',
                'origin_city' => 'Sydney',
                'origin_country' => 'Australia',
                'origin_country_code' => 'AU',
                'origin_lat' => -33.9461,
                'origin_lng' => 151.1772,
                'destination_port' => 'Los Angeles Airport',
                'destination_city' => 'Los Angeles',
                'destination_country' => 'United States',
                'destination_country_code' => 'US',
                'destination_lat' => 33.9416,
                'destination_lng' => -118.4085,
                'current_lat' => 33.9416,
                'current_lng' => -118.4085,
                'status' => 'Customs Cleared',
                'risk_level' => 'Low',
                'transport_mode' => 'Air',
                'eta' => '2026-07-02 12:00:00',
                'carrier_name' => 'Qantas Freight',
                'vessel_name' => 'Airbus A330-200F',
                'imo_number' => 'A-QF330',
                'speed' => 0.0,
                'heading' => 0,
                'container_temp_history' => [5, 5, 4, 4, 4, 4, 4, 4, 4, 4],
                'container_humidity_history' => [45, 44, 45, 46, 45, 44, 45, 45, 46, 45],
                'document_bill_of_lading' => 'Approved',
                'document_certificate_of_origin' => 'Approved',
                'document_commercial_invoice' => 'Approved',
                'document_packing_list' => 'Approved',
                'document_customs_declaration' => 'Approved',
                'value' => 84000.00,
                'currency' => 'AUD',
            ],
            [
                'cargo_id' => 'CRG-2026-BR08',
                'origin_port' => 'Port of Santos',
                'origin_city' => 'Santos',
                'origin_country' => 'Brazil',
                'origin_country_code' => 'BR',
                'origin_lat' => -23.9608,
                'origin_lng' => -46.3336,
                'destination_port' => 'Port of Antwerp',
                'destination_city' => 'Antwerp',
                'destination_country' => 'Belgium',
                'destination_country_code' => 'BE',
                'destination_lat' => 51.2194,
                'destination_lng' => 4.4025,
                'current_lat' => -2.3333,
                'current_lng' => -32.1167,
                'status' => 'In-Transit',
                'risk_level' => 'Medium',
                'transport_mode' => 'Sea',
                'eta' => '2026-07-18 09:30:00',
                'carrier_name' => 'MSC',
                'vessel_name' => 'MSC Gülsün',
                'imo_number' => '9839430',
                'speed' => 16.8,
                'heading' => 38,
                'container_temp_history' => [25, 26, 26, 27, 27, 28, 28, 29, 29, 29],
                'container_humidity_history' => [72, 73, 75, 76, 78, 80, 82, 82, 83, 85],
                'document_bill_of_lading' => 'Approved',
                'document_certificate_of_origin' => 'Approved',
                'document_commercial_invoice' => 'Approved',
                'document_packing_list' => 'Approved',
                'document_customs_declaration' => 'Under Review',
                'value' => 6200000.00,
                'currency' => 'BRL',
            ],
        ];

        // Supply chain and global logistics news (News Intelligence parameter)
        $news = [
            [
                'title' => 'Suez Canal Transit Volumes Recover by 12% in Q2',
                'source' => 'Maritime Executive',
                'summary' => 'Improved security escorts and stabilizing insurance premiums draw bulk cargo carriers back to the traditional trade shortcut.',
                'timestamp' => '2 hours ago',
                'risk' => 'Low',
            ],
            [
                'title' => 'Rotterdam Port Congestion Index Climbs to 7.4',
                'source' => 'Port Technology',
                'summary' => 'Automated terminal upgrades and digital customs clearance bottlenecks cause container vessel waiting times to exceed 48 hours.',
                'timestamp' => '4 hours ago',
                'risk' => 'High',
            ],
            [
                'title' => 'Global Freight Rates Dip 3% Amid Easing Fuel Surcharges',
                'source' => 'Drewry Logistics Report',
                'summary' => 'Weakening trans-pacific spot rates offset peak season demand spikes, stabilizing operating container transport costs.',
                'timestamp' => '1 day ago',
                'risk' => 'Low',
            ],
            [
                'title' => 'Customs Strikes Looming in North Sea Ports',
                'source' => 'Reuters Trade',
                'summary' => 'Labor disputes in Hamburg and Antwerp trade unions threaten cargo processing throughput times next week.',
                'timestamp' => '1 day ago',
                'risk' => 'Medium',
            ],
        ];

        // World Bank Economic Trade Profiles (World Bank Data parameter)
        $worldBankData = [
            'CN' => ['name' => 'China', 'gdp_trillions' => 17.96, 'lpi_rank' => 20, 'trade_pct_gdp' => 37.4, 'customs_score' => 3.5],
            'US' => ['name' => 'United States', 'gdp_trillions' => 25.46, 'lpi_rank' => 17, 'trade_pct_gdp' => 25.3, 'customs_score' => 3.8],
            'DE' => ['name' => 'Germany', 'gdp_trillions' => 4.07, 'lpi_rank' => 3, 'trade_pct_gdp' => 98.7, 'customs_score' => 4.1],
            'ID' => ['name' => 'Indonesia', 'gdp_trillions' => 1.32, 'lpi_rank' => 61, 'trade_pct_gdp' => 45.2, 'customs_score' => 3.1],
            'JP' => ['name' => 'Japan', 'gdp_trillions' => 4.23, 'lpi_rank' => 13, 'trade_pct_gdp' => 46.8, 'customs_score' => 3.9],
            'SG' => ['name' => 'Singapore', 'gdp_trillions' => 0.47, 'lpi_rank' => 1, 'trade_pct_gdp' => 337.8, 'customs_score' => 4.3],
            'NL' => ['name' => 'Netherlands', 'gdp_trillions' => 1.00, 'lpi_rank' => 2, 'trade_pct_gdp' => 172.5, 'customs_score' => 4.2],
            'GB' => ['name' => 'United Kingdom', 'gdp_trillions' => 3.07, 'lpi_rank' => 19, 'trade_pct_gdp' => 60.1, 'customs_score' => 3.7],
            'AU' => ['name' => 'Australia', 'gdp_trillions' => 1.68, 'lpi_rank' => 18, 'trade_pct_gdp' => 47.9, 'customs_score' => 3.6],
            'BE' => ['name' => 'Belgium', 'gdp_trillions' => 0.58, 'lpi_rank' => 5, 'trade_pct_gdp' => 194.2, 'customs_score' => 4.0],
            'BR' => ['name' => 'Brazil', 'gdp_trillions' => 1.92, 'lpi_rank' => 51, 'trade_pct_gdp' => 39.1, 'customs_score' => 2.9],
        ];

        return view('dashboard', compact('shipments', 'news', 'worldBankData'));
    }
}
